# Login User
POST http://localhost:8081/api/v1/login
Content-Type: application/json

{
    "email": "jeraldvictor123@yahoo.com",
    "password": "Jerald@11"
}

###

# Register User
POST http://localhost:8081/api/v1/register
Content-Type: application/json

{
    "username": "Jerald",
    "email": "jeraldvictor123@yahoo.com",
    "password": "Jerald@11"
}